steps:
  - block: "Deploy $BUILDKITE_COMMIT (PR: $BUILDKITE_PULL_REQUEST) to Staging"

  - label: "Pushing to articles to staging"
    commands:
      - "npm install @stoplight/cli@5"
      - "npx --yes @stoplight/cli@5 push --ci-token $SECRET_STOPLIGHT_DEVELOPER_DOCS_CI_TOKEN_STAGING"
    plugins:
      # Using the plain Node image, instead of the custom doc Dockerfile
      # version, is way faster because we don't have to wait for Ruby gems to
      # install.
      - docker#v3.5.0:
          image: "node:alpine"

pd-meta: # Used by Buildkite Pipeline Manager (https://github.com/PagerDuty/buildkite-pipeline-manager)
  name: "Developer Docs Staging"
  teams:
    - "All"
    - "SHAF Shared"
